"""setup bd

Revision ID: 9b67b60689b2
Revises: 
Create Date: 2026-05-17 17:25:40.681710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b67b60689b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chinese_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('new_year', 'golden_week', 'mid_autumn', 'qingming', 'dragon_boat', 'factory_off', 'custom', name='chinese_event_type'), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='chinese_event_severity'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chinese_events', schema=None) as batch_op:
        batch_op.create_index('ix_chinese_events_year_date', ['year', 'date_start'], unique=False)

    op.create_table('community_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('telegram', 'whatsapp', 'tiktok', name='community_platform'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('dial_code', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('flag_emoji', sa.String(length=10), nullable=True),
    sa.Column('is_served', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('hero_image_public_id', sa.String(length=255), nullable=True),
    sa.Column('hero_image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('page', sa.Enum('homepage', 'community', 'about', name='stat_page'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stats_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_stats_page'), ['page'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('store_link', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('contact_wechat', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('avg_delivery_days', sa.Integer(), nullable=True),
    sa.Column('success_rate_pct', sa.Float(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_amount_cny', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_expires_at'), ['expires_at'], unique=False)

    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_logs_created_at'), ['created_at'], unique=False)

    op.create_table('course_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('duration_label', sa.String(length=50), nullable=True),
    sa.Column('is_preview', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_modules_course_id'), ['course_id'], unique=False)

    op.create_table('course_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('max_seats', sa.Integer(), nullable=True),
    sa.Column('current_seats', sa.Integer(), nullable=True),
    sa.Column('whatsapp_group_link', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'open', 'full', 'in_progress', 'completed', 'cancelled', name='course_session_status'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_sessions_course_id'), ['course_id'], unique=False)

    op.create_table('course_testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('session_label', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_testimonials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_testimonials_course_id'), ['course_id'], unique=False)

    op.create_table('customs_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('threshold_amount_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_pct', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customs_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customs_rules_country_code'), ['country_code'], unique=False)

    op.create_table('product_category_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('surcharge_per_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('surcharge_type', sa.Enum('PER_KG', 'FIXED', 'NONE', name='surcharge_type'), nullable=False),
    sa.Column('customs_rate_pct', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_category_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category_rules_country_code'), ['country_code'], unique=False)

    op.create_table('service_fee_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('min_amount_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_amount_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_fee_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_fee_rules_country_code'), ['country_code'], unique=False)

    op.create_table('shipping_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timeframe_days_min', sa.Integer(), nullable=True),
    sa.Column('timeframe_days_max', sa.Integer(), nullable=True),
    sa.Column('price_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'name', name='uq_shipping_country_name')
    )
    with op.batch_alter_table('shipping_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_methods_country_code'), ['country_code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('client', 'operator', 'super_admin', name='user_role'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('preferred_otp_channel', sa.Enum('sms', 'whatsapp', 'email', name='otp_channel'), nullable=False),
    sa.Column('avatar_public_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_whatsapp'), ['whatsapp'], unique=False)

    op.create_table('waves',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('shipping_date', sa.Date(), nullable=False),
    sa.Column('arrival_date_min', sa.Date(), nullable=False),
    sa.Column('arrival_date_max', sa.Date(), nullable=False),
    sa.Column('transport_type', sa.String(length=100), nullable=True),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_load_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'OPEN', 'CLOSED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='wave_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waves_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_waves_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('types_disabled', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('channel', sa.Enum('in_app', 'email', 'whatsapp', name='notification_channel'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('sms', 'whatsapp', 'email', name='otp_channel'), nullable=True),
    sa.Column('reset_token', sa.String(length=36), nullable=True),
    sa.Column('reset_token_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reset_token')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_label', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_number', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('target_wave_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'QUOTED', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED', 'ORDERED', 'CANCELLED', name='request_status'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_wave_id'], ['waves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_request_number'), ['request_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_target_wave_id'), ['target_wave_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_user_id'), ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Enum('string', 'int', 'bool', 'json', name='setting_value_type'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_category'), ['category'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_number', sa.String(length=30), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED', 'EXPIRED', name='quotation_status'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate_cny_fcfa', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('total_products_cost_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_shipping_cost_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_service_fee_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_customs_fee_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_other_fee_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('applied_service_fee_tier_pct', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('pdf_public_id', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_quotation_number'), ['quotation_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_quotations_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_status'), ['status'], unique=False)

    op.create_table('request_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('supplier_link', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('target_price_cny', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_items_request_id'), ['request_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wave_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CONFIRMED', 'SUPPLIER_ORDERED', 'IN_TRANSIT_CN', 'SHIPPED', 'CUSTOMS', 'DELIVERED', 'ISSUE', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('total_amount_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('has_issue', sa.Boolean(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('supplier_received_at', sa.DateTime(), nullable=True),
    sa.Column('in_transit_cn_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('customs_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wave_id'], ['waves.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_wave_id'), ['wave_id'], unique=False)

    op.create_table('quotation_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('amount_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_costs_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('request_item_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_cost_cny', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_cost_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_per_unit_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('customs_per_unit_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subtotal_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_item_id'], ['request_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_items_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_items_request_item_id'), ['request_item_id'], unique=False)

    op.create_table('quotation_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_revisions_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('request_item_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['request_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_item_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_item_images_item_id'), ['item_id'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('subject', sa.Enum('info', 'order_issue', 'partnership', 'complaint', 'other', name='contact_subject'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'read', 'in_progress', 'resolved', name='contact_status'), nullable=True),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_user_id'), ['user_id'], unique=False)

    op.create_table('gallery_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('thumb_url', sa.Text(), nullable=False),
    sa.Column('full_url', sa.Text(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('wave_id', sa.String(length=50), nullable=True),
    sa.Column('description_short', sa.String(length=255), nullable=True),
    sa.Column('description_long', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wave_id'], ['waves.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_items_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_items_wave_id'), ['wave_id'], unique=False)

    op.create_table('order_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_messages_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_messages_sender_user_id'), ['sender_user_id'], unique=False)

    op.create_table('order_tracking_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_tracking_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_tracking_events_order_id'), ['order_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('method', sa.Enum('MTN_MOMO', 'ORANGE_MONEY', 'WAVE', 'AIRTEL', 'MOOV', 'CARD', 'BANK_TRANSFER', name='payment_method'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('internal_ref', sa.String(length=100), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('flutterwave_tx_id', sa.String(length=255), nullable=True),
    sa.Column('flutterwave_charge_response', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_ref')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('supplier_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_platform', sa.String(length=100), nullable=True),
    sa.Column('supplier_link', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate_snapshot', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_orders_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('contact_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_via', sa.Enum('email', 'whatsapp', 'internal', name='contact_reply_channel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['contact_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_replies_message_id'), ['message_id'], unique=False)

    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'validated', 'refunded', 'failed', name='enrollment_payment_status'), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_public_id', sa.String(length=255), nullable=True),
    sa.Column('certificate_url', sa.Text(), nullable=True),
    sa.Column('certificate_issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_session_id', 'user_id', name='uq_enrollment_session_user')
    )
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_enrollments_course_session_id'), ['course_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('gallery_testimonials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gallery_item_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('photo_public_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('date_label', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_item_id'], ['gallery_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_testimonials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_testimonials_gallery_item_id'), ['gallery_item_id'], unique=False)

    op.create_table('supplier_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_order_id'], ['supplier_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_order_items_supplier_order_id'), ['supplier_order_id'], unique=False)

    op.create_table('supplier_order_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_order_id'], ['supplier_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_order_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_order_tracking_supplier_order_id'), ['supplier_order_id'], unique=False)

    op.create_table('module_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'done', name='module_progress_status'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['course_enrollments.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'module_id', name='uq_progress_enrollment_module')
    )
    with op.batch_alter_table('module_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_progress_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_progress_module_id'), ['module_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_progress_module_id'))
        batch_op.drop_index(batch_op.f('ix_module_progress_enrollment_id'))

    op.drop_table('module_progress')
    with op.batch_alter_table('supplier_order_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_order_tracking_supplier_order_id'))

    op.drop_table('supplier_order_tracking')
    with op.batch_alter_table('supplier_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_order_items_supplier_order_id'))

    op.drop_table('supplier_order_items')
    with op.batch_alter_table('gallery_testimonials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_testimonials_gallery_item_id'))

    op.drop_table('gallery_testimonials')
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_enrollments_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_enrollments_course_session_id'))

    op.drop_table('course_enrollments')
    with op.batch_alter_table('contact_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_replies_message_id'))

    op.drop_table('contact_replies')
    with op.batch_alter_table('supplier_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_orders_order_id'))

    op.drop_table('supplier_orders')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    with op.batch_alter_table('order_tracking_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_tracking_events_order_id'))

    op.drop_table('order_tracking_events')
    with op.batch_alter_table('order_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_messages_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_messages_order_id'))

    op.drop_table('order_messages')
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_items_wave_id'))
        batch_op.drop_index(batch_op.f('ix_gallery_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_gallery_items_country_code'))

    op.drop_table('gallery_items')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('request_item_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_item_images_item_id'))

    op.drop_table('request_item_images')
    with op.batch_alter_table('quotation_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_revisions_quotation_id'))

    op.drop_table('quotation_revisions')
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_items_request_item_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_items_quotation_id'))

    op.drop_table('quotation_items')
    with op.batch_alter_table('quotation_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_costs_quotation_id'))

    op.drop_table('quotation_costs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_wave_id'))
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_request_id'))
        batch_op.drop_index(batch_op.f('ix_orders_quotation_id'))

    op.drop_table('orders')
    with op.batch_alter_table('request_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_items_request_id'))

    op.drop_table('request_items')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_status'))
        batch_op.drop_index(batch_op.f('ix_quotations_request_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_quotation_number'))
        batch_op.drop_index(batch_op.f('ix_quotations_country_code'))

    op.drop_table('quotations')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_category'))

    op.drop_table('system_settings')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_requests_target_wave_id'))
        batch_op.drop_index(batch_op.f('ix_requests_status'))
        batch_op.drop_index(batch_op.f('ix_requests_request_number'))
        batch_op.drop_index(batch_op.f('ix_requests_country_code'))

    op.drop_table('requests')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('waves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waves_status'))
        batch_op.drop_index(batch_op.f('ix_waves_country_code'))

    op.drop_table('waves')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_whatsapp'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_country_code'))

    op.drop_table('users')
    with op.batch_alter_table('shipping_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_methods_country_code'))

    op.drop_table('shipping_methods')
    with op.batch_alter_table('service_fee_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_fee_rules_country_code'))

    op.drop_table('service_fee_rules')
    with op.batch_alter_table('product_category_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category_rules_country_code'))

    op.drop_table('product_category_rules')
    with op.batch_alter_table('customs_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customs_rules_country_code'))

    op.drop_table('customs_rules')
    with op.batch_alter_table('course_testimonials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_testimonials_course_id'))

    op.drop_table('course_testimonials')
    with op.batch_alter_table('course_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_sessions_course_id'))

    op.drop_table('course_sessions')
    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_modules_course_id'))

    op.drop_table('course_modules')
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_logs_created_at'))

    op.drop_table('webhook_logs')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_expires_at'))

    op.drop_table('token_blacklist')
    op.drop_table('suppliers')
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_page'))
        batch_op.drop_index(batch_op.f('ix_stats_key'))

    op.drop_table('stats')
    op.drop_table('exchange_rates')
    op.drop_table('courses')
    op.drop_table('countries')
    op.drop_table('community_stats')
    op.drop_table('community_channels')
    with op.batch_alter_table('chinese_events', schema=None) as batch_op:
        batch_op.drop_index('ix_chinese_events_year_date')

    op.drop_table('chinese_events')
    # ### end Alembic commands ###
